version: '3.1'
services:
  mysql-db:
    image: mysql:5.7.18
    container_name: mysql-standalone
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    ports:
    - "3306:3306"
  productservice:
    image: spring-boot-mysql-docker
    container_name: spring-boot-mysql-docker-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/product_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
